"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utils_1 = require("./utils");
console.log("capitalize:", utils_1.stringUtils.capitalize("typescript"));
console.log("trim:", utils_1.stringUtils.trim("   Hello World   "));
console.log("repeat:", utils_1.stringUtils.repeat("abc", 3));
console.log("toSnakeCase:", utils_1.stringUtils.toSnakeCase("Hello World Again"));
console.log("toUpperCase:", utils_1.stringUtils.toUpperCase("hello"));
console.log("toLowerCase:", utils_1.stringUtils.toLowerCase("HELLO"));
console.log("isEmpty (пустая строка):", utils_1.stringUtils.isEmpty("    "));
console.log("isEmpty (непустая строка):", utils_1.stringUtils.isEmpty("content"));
console.log("reverseString:", utils_1.stringUtils.reverseString("abcdef"));
console.log("truncate:", utils_1.stringUtils.truncate("This is a long text", 10));
console.log("removeSpaces:", utils_1.stringUtils.removeSpaces("a b c d e f"));
console.log("countWords:", utils_1.stringUtils.countWords("one two three four"));
console.log("startsWith (true):", utils_1.stringUtils.startsWith("TypeScript", "Type"));
console.log("startsWith (false):", utils_1.stringUtils.startsWith("TypeScript", "Script"));
console.log("endsWith (true):", utils_1.stringUtils.endsWith("TypeScript", "Script"));
console.log("endsWith (false):", utils_1.stringUtils.endsWith("TypeScript", "Type"));
console.log("replaceAll:", utils_1.stringUtils.replaceAll("hello hello world", "hello", "hi"));
